name: todo_flutter
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^5.13.0
  provider: ^6.0.5
  table_calendar: ^3.0.9


development_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
